Repository InTouch-Val/INtouch, pull requests merged in 2024-09, with the labels that each got.

#388 change update date to add_date
  frontend/src/components/psy/AssignmentTile/AssignmentTile.tsx
Labels: fix

#389 refetch card after delete card
  frontend/src/components/psy/AssignmentTile/AssignmentTile.tsx
Labels: bug

#390 fix name emotion
  frontend/src/components/psy/DiaryPageContent/DiaryBlockEmotion/constants.ts
Labels: bug

#395 fix: emotions typos
  backend/api/constants.py
  backend/api/migrations/0028_alter_diarynote_clarifying_emotion.py
Labels: backend, fix

#401 feature: increase title length
  backend/api/migrations/0029_alter_assignment_title_alter_assignmentclient_title.py
  backend/api/models.py
Labels: backend

#391 Feat/ tumbler componet
  frontend/src/components/client/ClientAssignmentCard/ClientAssignmentCard.tsx
  frontend/src/components/client/CompleteAssignments/CompleteAssignments.tsx
  frontend/src/components/client/MyDiary/CardDiary/CardDiary.tsx
  frontend/src/components/psy/ClientDetailsPage.tsx
  frontend/src/global.d.ts
  frontend/src/routes/AssignmentsPageRefactor/TabsAssignments/Hoc.tsx
  frontend/src/routes/AssignmentsPageRefactor/TabsAssignments/Tab.tsx
  frontend/src/routes/client-page.tsx
  frontend/src/stories/tumbler/Tumbler.stories.ts
  frontend/src/stories/tumbler/Tumbler.tsx
  frontend/src/stories/tumbler/style.module.scss
  frontend/src/utils/notification-texts.json
Labels: bug, fix

#405 Fix/onboarding mobile
  frontend/src/components/client/ClientAssignments.tsx
  frontend/src/components/psy/ClientDetailsPage.tsx
  frontend/src/components/psy/HeaderAssigmentPage/HeaderAssignment.scss
  frontend/src/css/assignments.scss
  frontend/src/css/block.scss
  frontend/src/css/image-selector.module.scss
  frontend/src/scss-styles/variables.scss
  frontend/src/utils/hook/useMobileWidth.js
Labels: frontend
